theme: jekyll-theme-architect

#Prose.io editing info
repo_name: tobago
branch: master
#GitHub organization name *or* username
gh_org: gbinal
prose_url: https://github.com/
site_url: https://www.github.com
media: assets/img
